name: Learning github actions

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: cat datapackage.json

      - run: head data/estados.csv

      - name: Set branch name
        id: branch
        run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"

      - name: Get color
        run: echo "The current branch is ${{ steps.branch.outputs.BRANCH_NAME }}"