name: Learning github actions

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set branch name
        id: branch
        run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - run: Rscript -e 'install.packages("rmarkdown")'

      - run: Rscript scripts/build.R ${{ steps.branch.outputs.BRANCH_NAME }}

      - run: git checkout gh-pages
      - run: git add ${{ steps.branch.outputs.BRANCH_NAME }}/*
      - run: |
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git commit -m "Atualiza branch ${{ steps.branch.outputs.BRANCH_NAME }}"
      - run: git push origin gh-pages
